# Site settings
title: Maye Zhang
# description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# url: "https://mayezhang.github.io/"
# User settings
username: Ch Zhang
# user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff.
user_title: Communication Engineering @ HIT
email: ch.zhang@hit.edu.cn
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
github_username:  Maye Zhang
exclude: ['package.json', 'src' , 'node_modules']
